name:                pacman-minimax
version:             0.1.0.0
github:              "jonathanychen/pacman-minimax"
license:             BSD-3-Clause
author:              "Jonathan Chen, Kevin Wang"
maintainer:          "jyc2183@columbia.edu, kjw2169@columbia.edu"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/jonathanychen/pacman-minimax#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- random
- deepseq
- vector
- parallel
- time

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  pacman-minimax-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pacman-minimax

tests:
  pacman-minimax-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pacman-minimax
